### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by moltar** [skyhookadventure/cdk-lambda-nodejs-mock#1]
Configured using `moduleNameMapper`, as suggested in the docs.

The only odd thing I am doing is using a custom transform:

```js
  transform: {
    '^.+\\.(t|j)sx?$': ['@swc-node/jest', { dynamicImport: true }],
  },
```

Getting the following error:

```
  ● cdk snapshot › matches snapshot

    RangeError: Maximum call stack size exceeded

      at Object.get [as LogLevel] (node_modules/cdk-lambda-nodejs-mock/dist/index.js:35:83)
      at Object.get [as LogLevel] (node_modules/cdk-lambda-nodejs-mock/dist/index.js:35:110)
      at Object.get [as LogLevel] (node_modules/cdk-lambda-nodejs-mock/dist/index.js:35:110)
      at Object.get [as LogLevel] (node_modules/cdk-lambda-nodejs-mock/dist/index.js:35:110)
      at Object.get [as LogLevel] (node_modules/cdk-lambda-nodejs-mock/dist/index.js:35:110)
      at Object.get [as LogLevel] (node_modules/cdk-lambda-nodejs-mock/dist/index.js:35:110)
      at Object.get [as LogLevel] (node_modules/cdk-lambda-nodejs-mock/dist/index.js:35:110)
      at Object.get [as LogLevel] (node_modules/cdk-lambda-nodejs-mock/dist/index.js:35:110)
      at Object.get [as LogLevel] (node_modules/cdk-lambda-nodejs-mock/dist/index.js:35:110)
      at Object.get [as LogLevel] (node_modules/cdk-lambda-nodejs-mock/dist/index.js:35:110)
```

Line 35 is the following:

```js
Object.defineProperty(exports, "LogLevel", { enumerable: true, get: function () { return aws_lambda_nodejs_1.LogLevel; } });
```

Any ideas?

**Comment by alan-cooney** [comment]
Hi @moltar - I don't think @swc-node supports ENUMs yet? 

https://github.com/Brooooooklyn/swc-node/issues/55

However given it's a call stack size error it may also be e.g. a memory leak - definitely worth re-running if you haven't already to see if you get a different error.

**Comment by moltar** [comment]
> I don't think @swc-node supports ENUMs yet?

Yeah, might be it. However, the tests work without the `cdk-lambda-nodejs-mock`, they just do the build step.

> However given it's a call stack size error it may also be e.g. a memory leak - definitely worth re-running if you haven't already to see if you get a different error.

I did re-run several times and the error is always the same.

**Comment by alan-cooney** [comment]
I think that's it I'm afraid -closing as it's an issue with swc-node rather than this module
